# Generated by Django 3.1.4 on 2020-12-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('fechaNacimiento', models.DateField()),
                ('trabajo', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('web', models.CharField(max_length=250, null=True)),
                ('identificacion', models.CharField(max_length=15, null=True)),
                ('foto', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=150)),
                ('contrasenia', models.CharField(max_length=150)),
                ('codPersona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='AgendaAPP.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPersona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Contacto', to='AgendaAPP.persona')),
            ],
        ),
    ]
