# Generated by Django 3.1.4 on 2020-12-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoGrupoContactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAPP.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Hogar', 'Hogar'), ('Celular', 'Celular'), ('Otros', 'Otros')], default='Celular', max_length=100)),
                ('operador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTelefono', models.CharField(default='000000000', max_length=15)),
                ('codPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAPP.persona')),
                ('detalleTelefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAPP.detalletelefono')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoContactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrupo', models.CharField(max_length=150)),
                ('codUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAPP.usuario')),
                ('contactos', models.ManyToManyField(through='AgendaAPP.ContactoGrupoContactos', to='AgendaAPP.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDireccion', models.CharField(choices=[('Casa', 'Casa'), ('Trabajo', 'Trabajo'), ('Otros', 'Otros')], default='Casa', max_length=50)),
                ('direccion', models.CharField(max_length=500)),
                ('codPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAPP.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CorreoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.EmailField(max_length=254)),
                ('codPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAPP.persona')),
            ],
        ),
        migrations.AddField(
            model_name='contactogrupocontactos',
            name='codGrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAPP.grupocontactos'),
        ),
    ]
